[package]
name = "openztna-application-connector"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "OpenZTNA Application Connector - Zero Trust Network Access application proxy component"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"
config = "0.13"
jsonwebtoken = "8.3"
tonic = "0.9"
prost = "0.11"
rustls = "0.21"
tokio-rustls = "0.24"