[package]
name = "openztna-control-plane"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "OpenZTNA Control Plane - Zero Trust Network Access central management component"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
actix-web = "4.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
env_logger = "0.10"
anyhow = "1.0"
thiserror = "1.0"
config = "0.13"
sqlx = { version = "0.7", features = ["runtime-tokio-rustls", "postgres", "uuid", "time", "json"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
jsonwebtoken = "8.3"
redis = { version = "0.23", features = ["tokio-comp"] }
tonic = "0.9"
prost = "0.11"